export enum OtpReason {
  RESET_PASSWORD = "RESET_PASSWORD",
  LOGIN = "LOGIN_OTP_SECRET",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  FORGET_PASSWORD = "FORGET_PASSWORD_SECRET",
  SIGNUP_OTP_SECRET = "SIGNUP_OTP_SECRET",
}
